/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Invoice.java
 *
 * Created on May 20, 2018, 7:40:50 AM
 */
package orangefruit;

/**
 *
 * @author Kushiya
 */
public class Dash extends javax.swing.JFrame {

    /** Creates new form Invoice */
    public Dash() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_invoice = new javax.swing.JButton();
        btn_delivery = new javax.swing.JButton();
        btn_grn = new javax.swing.JButton();
        btn_suppliers = new javax.swing.JButton();
        btn_addItem = new javax.swing.JButton();
        btn_reports = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Orange Fruit");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_invoice.setBackground(new java.awt.Color(255, 255, 255));
        btn_invoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Invoice-Recovered.jpg"))); // NOI18N
        btn_invoice.setText("Invoice");
        btn_invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_invoiceActionPerformed(evt);
            }
        });
        getContentPane().add(btn_invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 125, 143, 79));

        btn_delivery.setBackground(new java.awt.Color(255, 255, 255));
        btn_delivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Delivery-Recovered.jpg"))); // NOI18N
        btn_delivery.setText("Delivery");
        btn_delivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deliveryActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 279, 143, 79));

        btn_grn.setBackground(new java.awt.Color(255, 255, 255));
        btn_grn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/GRN.jpg"))); // NOI18N
        btn_grn.setText("GRN");
        btn_grn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grnActionPerformed(evt);
            }
        });
        getContentPane().add(btn_grn, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 433, 143, 79));

        btn_suppliers.setBackground(new java.awt.Color(255, 255, 255));
        btn_suppliers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Suppliers.jpg"))); // NOI18N
        btn_suppliers.setText("Suppliers");
        btn_suppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suppliersActionPerformed(evt);
            }
        });
        getContentPane().add(btn_suppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 125, 143, 79));

        btn_addItem.setBackground(new java.awt.Color(255, 255, 255));
        btn_addItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/AddItems.jpg"))); // NOI18N
        btn_addItem.setText("Add Item");
        btn_addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addItemActionPerformed(evt);
            }
        });
        getContentPane().add(btn_addItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 279, 143, 79));

        btn_reports.setBackground(new java.awt.Color(255, 255, 255));
        btn_reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Report-Recovered.jpg"))); // NOI18N
        btn_reports.setText("Reports");
        btn_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 433, 143, 79));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void btn_invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_invoiceActionPerformed
    new Invoice().setVisible(true);
}//GEN-LAST:event_btn_invoiceActionPerformed

private void btn_deliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deliveryActionPerformed
    new Delivery().setVisible(true);
}//GEN-LAST:event_btn_deliveryActionPerformed

private void btn_grnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grnActionPerformed
    new GRN().setVisible(true);
}//GEN-LAST:event_btn_grnActionPerformed

private void btn_suppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suppliersActionPerformed
    new Suppliers().setVisible(true);
}//GEN-LAST:event_btn_suppliersActionPerformed

private void btn_addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addItemActionPerformed
    new AddItem().setVisible(true);
}//GEN-LAST:event_btn_addItemActionPerformed

private void btn_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportsActionPerformed
    new Report().setVisible(true);
}//GEN-LAST:event_btn_reportsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Dash().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addItem;
    private javax.swing.JButton btn_delivery;
    private javax.swing.JButton btn_grn;
    private javax.swing.JButton btn_invoice;
    private javax.swing.JButton btn_reports;
    private javax.swing.JButton btn_suppliers;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
