/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Invoice.java
 *
 * Created on May 20, 2018, 7:40:50 AM
 */
package orangefruit;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kushiya
 */
public class GRN extends javax.swing.JFrame {

    DB db =  new DB();
    double uPrice;
    /** Creates new form Invoice */
    public GRN() {
        initComponents();
        auto_id();
        lbl_tot.setText("0.00");
        date_today();
    }

    void date_today(){
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        lbl_date.setText(sdf.format(date));
    }    
    
    void auto_id() {
        int num = 0;
        try {
            ResultSet r = db.getdata("select * from grn order by grnID");
            while (r.next()) {
                num = Integer.parseInt(r.getString("grnID"));

            }
        } catch (Exception e) {
            System.out.println(e);
        }
        int id = num + 1;
        lbl_grnID.setText("000" + id + "");
    }
    
    void clear(){
    txt_item.setText("");
    txt_nAmount.setText("");
    txt_quantity.setText("");
    txt_uPrice.setText("");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_grn = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_supplier = new javax.swing.JTextField();
        lbl_grnID = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_uPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_nAmount = new javax.swing.JTextField();
        btn_Add = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        lbl_tot = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_print = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_item = new javax.swing.JTextField();
        cmb_sup = new javax.swing.JComboBox();
        cmb_item = new javax.swing.JComboBox();
        lbl_date = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GRN");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_grn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item", "Unit Price", "Quantity", "Net Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_grn);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 246, 589, 221));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("GRN ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 70, -1, -1));

        txt_supplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_supplierKeyReleased(evt);
            }
        });
        getContentPane().add(txt_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 64, 145, -1));
        getContentPane().add(lbl_grnID, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 70, -1, -1));

        txt_quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_quantityKeyReleased(evt);
            }
        });
        getContentPane().add(txt_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 140, 152, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Supplier");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 67, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 143, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Unit Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 105, -1, -1));

        txt_uPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_uPriceKeyReleased(evt);
            }
        });
        getContentPane().add(txt_uPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 102, 145, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Net Amount");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 143, -1, -1));
        getContentPane().add(txt_nAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 140, 145, -1));

        btn_Add.setText("Add");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 187, 61, -1));

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 187, -1, -1));
        getContentPane().add(lbl_tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 485, 64, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 485, -1, -1));

        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        getContentPane().add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 517, 73, -1));

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 517, 72, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Item");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 105, -1, -1));

        txt_item.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_itemKeyReleased(evt);
            }
        });
        getContentPane().add(txt_item, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 102, 152, -1));

        cmb_sup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_supActionPerformed(evt);
            }
        });
        cmb_sup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmb_supKeyReleased(evt);
            }
        });
        getContentPane().add(cmb_sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 140, 10));

        cmb_item.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_itemActionPerformed(evt);
            }
        });
        cmb_item.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmb_itemKeyReleased(evt);
            }
        });
        getContentPane().add(cmb_item, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 140, 10));
        getContentPane().add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 130, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/790GRN.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
clear();
}//GEN-LAST:event_btn_clearActionPerformed

private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
    if(txt_supplier.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Insert Supplier!");
    else if(txt_item.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Insert Item!");
    else if(txt_uPrice.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Insert Price!");
    else if(txt_quantity.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Insert Quantity!");

    else
    {
            try {
                ResultSet r2 = db.getdata("select * from items where itemName like '" + txt_item.getText() + "%'");
                Vector v2 = new Vector();
                
                while (r2.next()){
                    v2.add(r2.getInt("itemID"));
                    DefaultTableModel d1 = (DefaultTableModel)tbl_grn.getModel();
                    d1.addRow(new Object[] { v2, txt_item.getText(), txt_uPrice.getText(), txt_quantity.getText(), txt_nAmount.getText() });
                    }
                } catch (Exception ex) {
                System.out.println(ex);
            }
        }
    
    double tot = Double.parseDouble(txt_nAmount.getText()) + Double.parseDouble(lbl_tot.getText());
    lbl_tot.setText(String.valueOf(new Double(tot)));
    clear();
}//GEN-LAST:event_btn_AddActionPerformed

private void txt_supplierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_supplierKeyReleased
    try {
            ResultSet r = db.getdata("select * from suppliers where supplierName like '" + txt_supplier.getText() + "%'");
            Vector v = new Vector();
            v.add("Select Name");
            while (r.next()) {

                v.add(r.getString("supplierName"));
                cmb_sup.setModel(new DefaultComboBoxModel(v));
                cmb_sup.setPopupVisible(true);
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
}//GEN-LAST:event_txt_supplierKeyReleased

private void txt_itemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_itemKeyReleased
    try {
            ResultSet r = db.getdata("select * from items where itemName like '" + txt_item.getText() + "%'");
            Vector v = new Vector();
            v.add("Select Item");
            while (r.next()) {

                v.add(r.getString("itemName"));
                cmb_item.setModel(new DefaultComboBoxModel(v));
                cmb_item.setPopupVisible(true);
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
}//GEN-LAST:event_txt_itemKeyReleased

private void cmb_supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_supActionPerformed
    try {
            ResultSet r = db.getdata("select * from suppliers where supplierName = '" + cmb_sup.getSelectedItem().toString() + "'");
            r.next();
            txt_supplier.setText(r.getString("supplierName"));
        } catch (Exception e) {
            System.out.println(e);
        }
}//GEN-LAST:event_cmb_supActionPerformed

private void cmb_supKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_supKeyReleased
    try {
            ResultSet r = db.getdata("select * from suppliers where supplierName = '" + cmb_sup.getSelectedItem().toString() + "'");
            r.next();
            txt_supplier.setText(r.getString("supplierName"));
        } catch (Exception e) {
            System.out.println(e);
        }
}//GEN-LAST:event_cmb_supKeyReleased

private void cmb_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_itemActionPerformed
    try {
            ResultSet r = db.getdata("select * from items where itemName = '" + cmb_item.getSelectedItem().toString() + "'");
            r.next();
            txt_item.setText(r.getString("itemName"));
        } catch (Exception e) {
            System.out.println(e);
        }
}//GEN-LAST:event_cmb_itemActionPerformed

private void cmb_itemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_itemKeyReleased
    try {
            ResultSet r = db.getdata("select * from items where itemName = '" + cmb_item.getSelectedItem().toString() + "'");
            r.next();
            txt_item.setText(r.getString("itemName"));
        } catch (Exception e) {
            System.out.println(e);
        }
}//GEN-LAST:event_cmb_itemKeyReleased

private void txt_uPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_uPriceKeyReleased
    uPrice = Double.parseDouble(txt_uPrice.getText());
}//GEN-LAST:event_txt_uPriceKeyReleased

private void txt_quantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantityKeyReleased
    int qty = Integer.parseInt(txt_quantity.getText());
    double amt = uPrice * qty;
    txt_nAmount.setText(String.valueOf(new Double(amt)));
}//GEN-LAST:event_txt_quantityKeyReleased

private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
    try {
        
            int row = tbl_grn.getSelectedRow();
            double value = Double.parseDouble(tbl_grn.getValueAt(row, 4).toString());
            double tot_new = Double.parseDouble(lbl_tot.getText()) - value;
            lbl_tot.setText(String.valueOf(tot_new));
        
            DefaultTableModel d2 = (DefaultTableModel) tbl_grn.getModel();
            int getindex = tbl_grn.getSelectedRow();
            int index = tbl_grn.convertRowIndexToModel(getindex);
            d2.removeRow(index);
            
            JOptionPane.showMessageDialog(null, "Item Deleted!");    
            
        } catch (Exception e) {
            System.out.println(e);
        }
}//GEN-LAST:event_btn_deleteActionPerformed

private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
    if(tbl_grn.getRowCount()==0){
        JOptionPane.showMessageDialog(null, "Insert Items!");
    }
    else
    try {
    
        DefaultTableModel d3 = (DefaultTableModel) tbl_grn.getModel();
        int rowc = d3.getRowCount();
    
            for(int i=0 ; i<rowc ; i++){
                    
                    String itemID = (d3.getValueAt(i, 0)).toString();
                    String itemName = (d3.getValueAt(i, 1)).toString();
                    String unPrice = (d3.getValueAt(i, 2)).toString();
                    String qty = (d3.getValueAt(i, 3)).toString();
                    String nAmount = (d3.getValueAt(i, 4)).toString();
                    
                    
                    db.putdata("insert into grn values ( '"+ lbl_grnID.getText() +"', '"+ txt_supplier.getText() +"', '"+ itemID +"', '"+ itemName +"', '"+ qty +"', '"+ unPrice +"', '"+ nAmount +"', '"+ lbl_date.getText() +"')");
                    db.putdata("insert into grntot values ('"+ lbl_grnID.getText() +"', '"+ lbl_date.getText() +"', '"+ lbl_tot.getText() +"')");
            } 
            
            JOptionPane.showMessageDialog(null, "Saved!");
            this.dispose();
            new GRN().setVisible(true);
        } 
        catch (Exception e) {
            System.out.println(e);
        }
}//GEN-LAST:event_btn_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GRN().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_print;
    private javax.swing.JComboBox cmb_item;
    private javax.swing.JComboBox cmb_sup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_grnID;
    private javax.swing.JLabel lbl_tot;
    private javax.swing.JTable tbl_grn;
    private javax.swing.JTextField txt_item;
    private javax.swing.JTextField txt_nAmount;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_supplier;
    private javax.swing.JTextField txt_uPrice;
    // End of variables declaration//GEN-END:variables
}
