/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Invoice.java
 *
 * Created on May 20, 2018, 7:40:50 AM
 */
package orangefruit;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kushiya
 */
public class Invoice extends javax.swing.JFrame {
   
    DB db = new DB();
    double uPrice;
    /** Creates new form Invoice */
    public Invoice() {
        initComponents();
        auto_id();
        lbl_tot.setText("0.00");
        date_today();
    }

    void date_today(){
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        lbl_date.setText(sdf.format(date));
    }
    
    void auto_id() {
        int num = 0;
        try {
            ResultSet r = db.getdata("select * from invoice order by invoiceID");
            while (r.next()) {
                num = Integer.parseInt(r.getString("invoiceID"));

            }
        } catch (Exception e) {
            System.out.println(e);
        }
        int id = num + 1;
        lbl_invoiceID.setText("000" + id + "");
    }
    
    void clear(){
        txt_item.setText("");
        txt_nAmount.setText("");
        txt_quantity.setText("");
        txt_uPrice.setText("");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_invoice = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_item = new javax.swing.JTextField();
        cmb_item = new javax.swing.JComboBox();
        lbl_invoiceID = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_uPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_nAmount = new javax.swing.JTextField();
        btn_Add = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        lbl_tot = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        lbl_date = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Invoice");
        setResizable(false);
        getContentPane().setLayout(null);

        tbl_invoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item", "Unit Price", "Quantity", "Net Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_invoice);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(102, 246, 589, 221);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Invoice ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(102, 70, 70, 14);

        txt_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_itemActionPerformed(evt);
            }
        });
        txt_item.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_itemKeyReleased(evt);
            }
        });
        getContentPane().add(txt_item);
        txt_item.setBounds(196, 102, 160, 20);

        cmb_item.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_itemActionPerformed(evt);
            }
        });
        cmb_item.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmb_itemKeyReleased(evt);
            }
        });
        getContentPane().add(cmb_item);
        cmb_item.setBounds(200, 110, 150, 10);
        getContentPane().add(lbl_invoiceID);
        lbl_invoiceID.setBounds(196, 70, 50, 10);

        txt_quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_quantityKeyReleased(evt);
            }
        });
        getContentPane().add(txt_quantity);
        txt_quantity.setBounds(196, 140, 160, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Item");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(102, 105, 50, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(102, 143, 60, 14);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Unit Price");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(410, 105, 70, 14);

        txt_uPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_uPriceKeyReleased(evt);
            }
        });
        getContentPane().add(txt_uPrice);
        txt_uPrice.setBounds(517, 102, 150, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Net Amount");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 143, 80, 14);
        getContentPane().add(txt_nAmount);
        txt_nAmount.setBounds(517, 140, 150, 20);

        btn_Add.setText("Add");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Add);
        btn_Add.setBounds(600, 190, 70, 23);

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear);
        btn_clear.setBounds(520, 190, 70, 23);
        getContentPane().add(lbl_tot);
        lbl_tot.setBounds(619, 485, 64, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Total");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(539, 485, 40, 14);

        btn_save.setText("Print");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save);
        btn_save.setBounds(618, 517, 73, 23);

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete);
        btn_delete.setBounds(528, 517, 72, 23);
        getContentPane().add(lbl_date);
        lbl_date.setBounds(660, 10, 130, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/800600.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(590, 180, 170, 140);
        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(290, 290, 330, 160);

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
    clear();
}//GEN-LAST:event_btn_clearActionPerformed

private void txt_itemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_itemKeyReleased
    try {
            ResultSet r = db.getdata("select * from items where itemName like '" + txt_item.getText() + "%'");
            Vector v = new Vector();
            v.add("Select Item");
            while (r.next()) {

                v.add(r.getString("itemName"));
                cmb_item.setModel(new DefaultComboBoxModel(v));
                cmb_item.setPopupVisible(true);
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
}//GEN-LAST:event_txt_itemKeyReleased

private void txt_uPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_uPriceKeyReleased
    uPrice = Double.parseDouble(txt_uPrice.getText());
}//GEN-LAST:event_txt_uPriceKeyReleased

private void txt_quantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantityKeyReleased
    int qty = Integer.parseInt(txt_quantity.getText());
    double amt = uPrice * qty;
    txt_nAmount.setText(String.valueOf(new Double(amt)));
}//GEN-LAST:event_txt_quantityKeyReleased

private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
    if(txt_item.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Insert Item!");
    else if(txt_uPrice.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Insert Price!");
    else if(txt_quantity.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Insert Quantity!");

    else
    {
            try {
                ResultSet r2 = db.getdata("select * from items where itemName like '" + txt_item.getText() + "%'");
                Vector v2 = new Vector();
                
                while (r2.next()){
                    v2.add(r2.getInt("itemID"));
                    DefaultTableModel d1 = (DefaultTableModel)tbl_invoice.getModel();
                    d1.addRow(new Object[] { v2, txt_item.getText(), txt_uPrice.getText(), txt_quantity.getText(), txt_nAmount.getText() });
                    }
                } catch (Exception ex) {
                System.out.println(ex);
            }
        }
    
    double tot = Double.parseDouble(txt_nAmount.getText()) + Double.parseDouble(lbl_tot.getText());
    lbl_tot.setText(String.valueOf(new Double(tot)));
    clear();
}//GEN-LAST:event_btn_AddActionPerformed

private void cmb_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_itemActionPerformed
    try {
            ResultSet r = db.getdata("select * from items where itemName = '" + cmb_item.getSelectedItem().toString() + "'");
            r.next();
            txt_item.setText(r.getString("itemName"));
        } catch (Exception e) {
            System.out.println(e);
        }
}//GEN-LAST:event_cmb_itemActionPerformed

private void cmb_itemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_itemKeyReleased
    try {
            ResultSet r = db.getdata("select * from items where itemName = '" + cmb_item.getSelectedItem().toString() + "'");
            r.next();
            txt_item.setText(r.getString("itemName"));
        } catch (Exception e) {
            System.out.println(e);
        }
}//GEN-LAST:event_cmb_itemKeyReleased

private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
    try {
        
            int row = tbl_invoice.getSelectedRow();
            double value = Double.parseDouble(tbl_invoice.getValueAt(row, 4).toString());
            double tot_new = Double.parseDouble(lbl_tot.getText()) - value;
            lbl_tot.setText(String.valueOf(tot_new));
        
            DefaultTableModel d2 = (DefaultTableModel) tbl_invoice.getModel();
            int getindex = tbl_invoice.getSelectedRow();
            int index = tbl_invoice.convertRowIndexToModel(getindex);
            d2.removeRow(index);
            
            JOptionPane.showMessageDialog(null, "Item Deleted!");    
            
        } catch (Exception e) {
            System.out.println(e);
        }
    

}//GEN-LAST:event_btn_deleteActionPerformed

private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed

    if(tbl_invoice.getRowCount()==0){
        JOptionPane.showMessageDialog(null, "Insert Items!");
    }
    else
    try {
    
        DefaultTableModel d3 = (DefaultTableModel) tbl_invoice.getModel();
        int rowc = d3.getRowCount();
    
            for(int i=0 ; i<rowc ; i++){
                    String itemID = (d3.getValueAt(i, 0)).toString();
                    String itemName = (d3.getValueAt(i, 1)).toString();
                    String unPrice = (d3.getValueAt(i, 2)).toString();
                    String qty = (d3.getValueAt(i, 3)).toString();
                    String nAmount = (d3.getValueAt(i, 4)).toString();
                    
                    
                    db.putdata("insert into invoice values ( '"+ lbl_invoiceID.getText() +"', '"+ itemID +"', '"+ itemName +"', '"+ unPrice +"', '"+ qty +"', '"+ nAmount +"', '"+ lbl_date.getText() +"')");
                    db.putdata("insert into invoicetot values ('"+ lbl_invoiceID.getText() +"', '"+ lbl_date.getText() +"', '"+ lbl_tot.getText() +"')");
            } 
            
            JOptionPane.showMessageDialog(null,  "Saved!");
            String invoiceid = lbl_invoiceID.getText();
            new InvoicePrint(invoiceid).setVisible(true);
            this.dispose();
            
        } 
        catch (Exception e) {
            System.out.println(e);
        }
               
        
   
}//GEN-LAST:event_btn_saveActionPerformed

    private void txt_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_itemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox cmb_item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_invoiceID;
    private javax.swing.JLabel lbl_tot;
    private javax.swing.JTable tbl_invoice;
    private javax.swing.JTextField txt_item;
    private javax.swing.JTextField txt_nAmount;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_uPrice;
    // End of variables declaration//GEN-END:variables
}
